version: "3"
services:
  nginx:
    restart: always # because it is routing traffic to our entire server
    container_name: 'nginx-server'
    image: nginx
    ports:
      - '80:80'
    networks:
      - private-network
  mongodb:
    image: 'mongo'
    restart: always
    container_name: 'mongo-db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    ports:
      - '27017-27019:27017-27019'
    volumes: 
      - ../.mongo-volume:/data/db
    networks:
      - private-network

  mysqldb:
    image: mariadb:10
    restart: always
    container_name: 'mysql-db'
    command:
      ["--character-set-server=utf8", "--collation-server=utf8_unicode_ci"]
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - ../.mysql-volume:/var/lib/mysql
    networks:
      - private-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    restart: always
    container_name: 'phpmyadmin-client'
    depends_on:
      - mysqldb
    environment:
      - PMA_HOST=mysql-db
      # - PMA_ABSOLUTE_URI=https://pma.localhost/
    networks:
      - private-network

networks:
  private-network:
    external: true