name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Docker compose up
      run: docker compose up --build --remove-orphans -d
    - name: Configuring nginx
      run: docker container cp ./phpmyadmin/phpmyadmin.conf nginx-server:/etc/nginx/conf.d/
    - run: docker container exec nginx-server nginx -s reload
