name: Docker Image CI

on:
  push:
    branches: ["master"]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  SSH_KEY: ${{ secrets.SSH_KEY }}
  SSH_TARGET: ec2-user@alexkander.xyz
  SSH_DIRECTORY: "/home/ec2-user"
  DB_PASS: ${{ secrets.DB_PASS }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Env
        run: |
          REPO_NAME=${GITHUB_REPOSITORY//\//_}
          RUN_TAG="${{ github.run_number }}.${{ github.run_attempt }}"

          echo "RUN_TAG=$RUN_TAG" >> $GITHUB_ENV
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

          echo "IMAGE_TAG=$RUN_TAG-${GITHUB_SHA::8}" >> $GITHUB_ENV
          echo "REPO_DIR=$SSH_DIRECTORY/$REPO_NAME" >> $GITHUB_ENV

      - name: Docker Stack Deploy
        env:
          STACK_ENV: "REPO_DIR=${{ env.REPO_DIR }} DB_PASS=${{ env.DB_PASS }}"
        run: |
          echo -e "$SSH_KEY" > __TEMP_KEY_FILE
          chmod 600 __TEMP_KEY_FILE
          scp -o StrictHostKeyChecking=no -i __TEMP_KEY_FILE -P 22 -v -r docker-stack.yml "$SSH_TARGET:$REPO_DIR/docker-stack.yml"
          scp -o StrictHostKeyChecking=no -i __TEMP_KEY_FILE -P 22 -v -r docker-stack.yml "$SSH_TARGET:$REPO_DIR/_docker-stack-history/docker-stack-$IMAGE_TAG.yml"

          scp -o StrictHostKeyChecking=no -i __TEMP_KEY_FILE -P 22 -v -r traefik.yml "$SSH_TARGET:$REPO_DIR/traefik.yml"
          scp -o StrictHostKeyChecking=no -i __TEMP_KEY_FILE -P 22 -v -r traefik.yml "$SSH_TARGET:$REPO_DIR/_traefik-history/traefik-$IMAGE_TAG.yml"

          ssh -o StrictHostKeyChecking=no -i __TEMP_KEY_FILE -p 22 $SSH_TARGET env $STACK_ENV docker stack deploy --prune -c "$REPO_DIR/docker-stack.yml" --with-registry-auth $REPO_NAME
